name: Android CI

on:
  push:
  pull_request:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref }}
        
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.100-preview.6.24328.19'
    
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Install Android NDK
      run: |
        mkdir -p $HOME/android-ndk
        wget https://dl.google.com/android/repository/android-ndk-r21-linux-x86_64.zip
        unzip android-ndk-r21-linux-x86_64.zip -d $HOME/android-ndk
        echo "NDK_HOME=$HOME/android-ndk/android-ndk-r21" >> $GITHUB_ENV
        
    - name: Grant execute permission for gradlew
      run: chmod +x src/RyujinxAndroid/gradlew

    - name: Build with Gradle
      run: cd src/RyujinxAndroid/ && ./gradlew build
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: src/RyujinxAndroid/app/
